### ISSUE TITLE
Issue with nested structure

### ISSUE THREAD

**Issue by quazzuk** [chmp/serde_arrow#15]
Hey

Nice project!

I'm just attempting to deserialize a nested structure (2 levels). I'm not sure whether this is supported(?) but I'm doing something similar with the csv serde and it just flattens the nested structure. Not sure whether something similar would be possible here or are nested structures supported by arrow/parquet?

Currently I'm getting the following error `Error: Cannot add_field with event StartMap`

Thanks

**Comment by quazzuk** [comment]
Apologies for the delay...

I ended up just flattening the structure then writing to parquet. Works like a charm!

Thanks

**Comment by chmp** [comment]
Nested structures are natively supported on the arrow2 branch. Close once released

**Comment by chmp** [comment]
Released with 0.6.0-rc.0
