### ISSUE TITLE
Update arrow dependency

### ISSUE THREAD

**Issue by oersted** [chmp/serde_arrow#17]
See: https://github.com/apache/arrow-rs/issues/2952#issuecomment-1293903593

**Comment by chmp** [comment]
Thanks for the hint. TBH. I am thinking of dropping arrow support alltogether in favor of arrow2. Mostly because of:

- the non-semver versioning policy of arrow makes it a huge hassle to support
- polars switched to arrow 2

**Comment by chmp** [comment]
Removed arrow support in favor of arrow2 with release 0.6.0-rc.0
