### ISSUE TITLE
Surface error more clearly for `push_validity`

### ISSUE THREAD

**Issue by kszlim** [chmp/serde_arrow#202]
When this function panics, it's not clear exactly what is being pushed that violates its invariants. Ideally you'd see what arrow field is failing and what the data looks like.

**Comment by chmp** [comment]
Thanks a lot for the report! The error messages are definitely something to improve. 

If you have a concrete example, it would be quite helpful, so I can directly include it in the test suite.

**Comment by chmp** [comment]
My current plan is to include the relevant fields (and potentially other metadata) in the error message, e.g., 

> Cannot push null for non-nullable array (field: "$.nested.field")

Would this have helped?

**Comment by chmp** [comment]
Released with 0.12.0
