### ISSUE TITLE
Bool8

### ISSUE THREAD

**Issue by v1gnesh** [chmp/serde_arrow#211]
Hey, I love seeing the recent updates. Hope you're doing well :handshake: 

When the new Bool8 type lands, please can you see if that can be added?

https://github.com/apache/arrow/pull/43234
https://github.com/apache/arrow/pull/43488
https://github.com/apache/arrow/pull/43323

**Comment by chmp** [comment]
Hey :)

Sure. As it's simply bools encoded as a 0/1 in a Int8 array, it should be a pretty trivial change.  (simply add bool support to the int deserializers / serializers). The extension type itself is ignored by the `serde_arrow` at the moment.

At the moment I am midway through a major change of the internals of serde_arrow, but I should be able to add this change afterwards.

**Comment by chmp** [comment]
Details from the PR defining the extension type:

> Bool8 represents a boolean value using 1 byte (8 bits) to store each value instead of only 1 bit as in the original Arrow Boolean type. Although less compact than the original representation, Bool8 may have better zero-copy compatibility with various systems that also store booleans using 1 byte.
>
> - Extension name: ``arrow.bool8``.
> - The storage type of this extension is ``Int8`` where:
>   - **false** is denoted by the value ``0``.
>   - **true** can be specified using any non-zero value. Preferably ``1``.
> - Extension type parameters: This type does not have any parameters.
> - Description of the serialization: Metadata is an empty string.

Impls:

- [ ] Test that `bool` can serialized / deserialized into `I8` arrays
- [ ] Test that any non-zero value is deserialized as `true`
- [ ] Implement extension type

**Comment by chmp** [comment]
Implemented with #212 and #214
