### ISSUE TITLE
jiff

### ISSUE THREAD

**Issue by v1gnesh** [chmp/serde_arrow#213]
Just wondering what you think about adding [jiff](https://docs.rs/jiff/latest/jiff/index.html) support.
This can go at the bottom of your priority list, of course.
Keen to hear if you know how jiff fares against chrono.
If there's one thing I've seen from polars PRs is that they mention chrono is not fast :)

**Comment by chmp** [comment]
Great idea! I have also been toying with the idea of using jiff in my my other projects due to the complexities of the chrono API. Definitely something to look into!

**Comment by chmp** [comment]
Started work on #243

**Comment by chmp** [comment]
Released with `0.12.1`
