### ISSUE TITLE
chrono's NaiveTime & Duration

### ISSUE THREAD

**Issue by v1gnesh** [chmp/serde_arrow#223]
From the [status page](https://docs.rs/serde_arrow/latest/serde_arrow/_impl/docs/status/index.html), I see that Arrow's types - `Time32`, `Time64`, and `Duration` are supported. How do I map chrono's `NaiveTime`, `Duration` to these types?

I see you've mentioned how chrono's `NaiveDateTime` is mapped to arrow DataType `Date64` in 2/3 strategies.

**EDIT:** I hope I'm interpreting this right... looks like you're already introducing this via https://github.com/chmp/serde_arrow/pull/218

**Comment by chmp** [comment]
Duration and NaiveTime and not yet on the road map. 

- Duration: I don't think chrono exposes a parser
- NaiveTime: should be easy to implement as chrono offers a parser

**Comment by chmp** [comment]
NaiveTime and NaiveDate were already supported, add support for `from_samples` and improved the docs in #239
