### ISSUE TITLE
Bring back the support for arrow-rs

### ISSUE THREAD

**Issue by elbaro** [chmp/serde_arrow#28]
While implementing a data source for DataFusion, I found this great library.
Unfortunately v0.5.0 does not support the list type, v0.6.0 added the support for lists and others but arrow2 is incompatible with DataFusion.

Until arrow-rs and arrow2 are merged, can you consider supporting arrow-rs or provide some compat utility to convert between arrow's RecordBatch and arrow2's Chunk?

https://docs.rs/datafusion/latest/datafusion/physical_plan/trait.RecordBatchStream.html

**Comment by chmp** [comment]
@elbaro Thanks for your comment. Re-adding arrow support again is definitely on my mental todo list. However, the non-semver compliance and very frequent releases of arrow-rs creates all kinds of work. I have not yet decided how to handle this.

In the meantime you could try to first build the arrow2 arrays and then convert them to arrow arrays via the FFI interface. Without having tested it you should be able to chain together these functions:

- [arrow2::ffi::export_field_to_c](https://docs.rs/arrow2/latest/arrow2/ffi/fn.export_field_to_c.html)
- [arrow2::ffi_export_array_to_ce](https://docs.rs/arrow2/latest/arrow2/ffi/fn.export_array_to_c.html)
- [arrow::ffi::ArrowArray::new](https://docs.rs/arrow/latest/arrow/ffi/struct.ArrowArray.html#method.new)

Something along the lines:

```rust
fn convert_arrow2_to_arrow(array: Box<dyn Array>, field: &Field) -> arrow::ffi::ArrowArray {
  let array = arrow2::ffi::export_array_to_c(array);
  let schema = arrow2::ffi::export_field_to_c(field);  

  let array = unsafe { std::mem::transmute<_, arrow::ffi::FFI_ArrowArray>(array) };
  let schema = unsafe { std::mem::transmute<_, arrow::ffi::FFI_ArrowSchema>(schema) };
  
  arrow::ffi::ArrowArray::new(array, schema)
}
```

**Comment by chmp** [comment]
You can find a fully worked example how to build a record batch from arrow2 arrays [here](https://github.com/chmp/serde_arrow/blob/fe0a9df9b0b82f15db7f495189c180a6a84531eb/arrow2-to-arrow/src/main.rs#L49).

**Comment by elbaro** [comment]
Thanks! With the example code I managed to export Rust types to datafusion.

```rs
struct A {
    f1: i64,
    f2: u32,
    f3: String,
    f4: Vec<u64>,
}
let items = vec![
    A {
        f1: 123,
        f2: 777,
        f3: "aaa".to_string(),
        f4: vec![100, 200, 300],
    },
    A {
        f1: 456,
        f2: 888,
        f3: "bbb".to_string(),
        f4: vec![400, 500, 600],
    },
];
let fields = serialize_into_fields(&items, TracingOptions::new())?;
let arrays = serialize_into_arrays(&fields, &items)?;

let batch = convert_to_record_batch(arrays, &fields)?;
let ctx = SessionContext::new();
ctx.register_batch("table1", batch)?;
let df = ctx.sql("SELECT * FROM table1").await?;
df.show().await?;
```

```
+-----+-----+-----+-----------------+
| f1  | f2  | f3  | f4              |
+-----+-----+-----+-----------------+
| 123 | 777 | aaa | [100, 200, 300] |
| 456 | 888 | bbb | [400, 500, 600] |
+-----+-----+-----+-----------------+
```

**Comment by chmp** [comment]
Implemented in `serde_arrow=0.6.0-rc.2`

**Comment by chmp** [comment]
@elbaro would you be up for an experiment?  I just published `serde_arrow=0.6.0-rc.2` with direct support for arrow serialization. You need to select the arrow version you would like to use by using the corresponding feature `arrow-35` or `arrow-36`. Then you can use `serde_arrow::arrow::*`. I will include a link to the docs, [once they are built](https://docs.rs/releases/queue).

**Comment by elbaro** [comment]
```rs
        let fields = serde_arrow::arrow::serialize_into_fields(
            &items,
            serde_arrow::schema::TracingOptions::new(),
        )?;
        let arrays = serde_arrow::arrow::serialize_into_arrays(&fields, &items)?;
        let batch = ::arrow::record_batch::RecordBatch::try_new(
            Arc::new(::arrow::datatypes::Schema::new(fields)),
            arrays,
        )?;
```

produced

```
Error: 
   0: Invalid argument error: column types must match schema types, expected
LargeList(Field { name: "element", data_type: UInt64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }) but found
LargeList(Field { name: "item", data_type: UInt64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) at column index 3
```

manually setting nullable to true of false didn't change the error.

```rs
fields = fields.into_iter().map(|f| f.with_nullable(true or false)).collect();
```

**Comment by chmp** [comment]
Thanks a lot for trying it out. This was super helpful: I added additional checks for the data types to the tests and there are issues in multiple places.

**Comment by chmp** [comment]
I pushed `v0.6.0-rc.3` with quite a bit of fixes. Now null handling should be more robust (and better tested).  At least in my tests your issues should be fixed.

**Comment by elbaro** [comment]
rc3 worked for the example. Option<> also worked.

```
struct A {
    f1: i64,
    f2: Option<u32>,
```

```
Field { name: "f1", data_type: Int64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} },
Field { name: "f2", data_type: UInt32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, 
```

**Comment by chmp** [comment]
Thanks for testing and the feedback!
