### ISSUE TITLE
Arrow-rs now generate schema & batches with json values of json file

### ISSUE THREAD

**Issue by jmfiaschi** [chmp/serde_arrow#8]
I just see that the [arrow-rs](https://github.com/apache/arrow-rs) can generate schema from json [file](https://github.com/apache/arrow-rs/blob/master/arrow/src/json/reader.rs#L301-L335)/buffer/[Vec<Result<Value>>](https://github.com/apache/arrow-rs/blob/master/arrow/src/json/reader.rs#L529-L550). With the schema, it is possible to use a decoder to create [batches ](https://github.com/apache/arrow-rs/blob/master/arrow/src/json/reader.rs#L552-L574).

Maybe It should be good to join the effort ?

**Comment by chmp** [comment]
Thanks for the head's up. I think the scope is a little bit different, but you're right. There is definitely some overlap. I will head over to the arrow repo and make folks aware. Maybe there is some interest to collab. 

At the moment, I working on deserialization and gravitate to base everything around a pull parser for a [JSON-like intermediate format](https://github.com/chmp/serde_arrow/blob/ed873975f098690a826ccd0b53c5221dc5134352/serde_arrow/src/test/deserialize.rs#L15). So there is even more overlap.

**Comment by chmp** [comment]
See discussion here: https://github.com/apache/arrow-rs/pull/1383#issuecomment-1059548659
