### ISSUE TITLE
Struct with String Field

### ISSUE THREAD

**Issue by Hergma** [chmp/serde_arrow#97]
Hi,
Thanks for this crate, really helpful.
I keep running into the below error when serializing a struct with String field, is that expected ?

```
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct A {
      pub B: String,
      pub K: f64,
}
let b = A{B:"TEST".to_string(), K:100.};

let fields = serialize_into_fields(&b, TracingOptions::default()).unwrap();
```

Invalid event Str("B") in state WaitForItem for StripOuterSequence

serde_arrow = {version="0.8.0", features = ["arrow2-0-17"]}
arrow2 = {version = "0.17", features = ["io_ipc"] }

**Comment by Hergma** [comment]
solved, b has to be a vector.

**Comment by chmp** [comment]
Thanks for the report. The error message should defintely be more self explanatory. 

I will add it to the todo list for the big "fix error messages" story.

**Comment by chmp** [comment]
Improved error message on main with #104
