### ISSUE TITLE
0.9.0-rc.1 is more picky figuring out schema from type

### ISSUE THREAD

**Issue by keltia** [chmp/serde_arrow#99]
Hello, trying to move from 0.8.0 to the new 0.9 API leads to fatal errors at run-time.  When using `SerdeArrowSchema::from_type`, it exits with the "deserialize_any is not supported" error message so you have to use `from_samples`.

https://github.com/keltia/fetiche-rs/blob/develop/formats/examples/parquet2.rs is the 0.8 version whereas https://github.com/keltia/fetiche-rs/blob/develop/formats/examples/parquet25.rs is the 0.9.0-rc.1 one.

The `Asd` struct is defined in [there](https://github.com/keltia/fetiche-rs/blob/3c5b0bd580a867f783ae9a88a12690fef2718243/formats/src/asd.rs#L29).

**Comment by chmp** [comment]
@keltia  Thanks a lot for already trying out the new version. While `from_type` is much easier to use than `from_samples` it does not work for all kind of types. In particular types that depend on the data in deserialization do not work. 

One example is `serde_json::Value`. `from_type` cannot know wether you intent to store a string, a float, or something else all together into it. My guess is that the pick first impl relies on a similar flexibility. Therefore `from_type` cannot work and you have to resort to either manually specifying the schema or using `from_samples`.

However, the error message is quite unhelpful. So I should definitely do sth. about that :)

**Comment by chmp** [comment]
Improved the error message in `from_type` on main. Will be released with `0.9.0`.
